---
- name: Install staginghelp script
# This is a basic Python script that prints out command reminders and links
# to Connect for more info.
  ignore_errors: yes
  copy:
    src: staginghelp
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: '0555'

- name: Copy staginghelp reminder script to /etc/profile.d
# This script runs at interactive login to remind users about the
# 'staginghelp' command.
  copy:
    src: staginghelpreminder.sh
    dest: /etc/profile.d
    owner: root
    group: root
    mode: '0644'
