- name: Rocky 8 Firewall for CS
  ignore_errors: yes
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - 80/tcp                                    # Java Console, Web Console, Command Center
    - 443/tcp                                   # https
    - 1433/tcp                                  # SQL Server
    - 8400/tcp                                  # cvd
    - 8401/tcp                                  # EvMgrS
    - 8403/tcp                                  # cvfwd