---
- name: CSRecoveryAssistant without CSDB restore
# If a CSDB database_path hasn't been provided, put the existing DB in staging 
# mode.
  command: "/opt/commvault/Base/CSRecoveryAssistant.sh -operation Staging -skipdump -disableallschedules -suspendalljobs -disableddbactivity"

- name: Get template's sPhysicalNodeName
# We'll need this below to run SetpreImagedNames.
  command: awk '/^sPhysicalNodeName / { print $2 }' /etc/CommVaultRegistry/Galaxy/Instance001/.properties
  register: old_name
  changed_when: False

- name: old_name=sPhysicalNodeName
# Object to string variable.
  set_fact:
    old_name: "{{ old_name.stdout }}"

- name: Update Commserve name to VM hostname
# Update the CS hostname in the DB to the hostname of the staging server.
  command: "/opt/commvault/Base/SetpreImagedNames CSNAME -instance Instance001 -hostname {{ fqdn }} {{ old_name }}"

- name: Set cs_timezone to UTC
  set_fact:
    cs_timezone: Etc/UTC
...