---
- name: Install gotty                             
# Install the HTTP-based terminal.
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  loop:
    - {src: 'gotty', dest: '/opt/staging/gotty/', mode: '0500'}               # gotty binary
    - {src: 'gotty.conf', dest: '/etc/gotty/', mode: '0500'}                  # gotty config file
    - {src: 'gotty.service', dest: '/etc/systemd/system/', mode: '0644'}      # gotty service file
    - {src: 'login.py', dest: '/opt/staging/gotty/', mode: '0500'}            # python login wrapper
    - {src: 'banner_template.ans', dest: '/etc/gotty/', mode: '0400'}         # gotty login banner
    - {src: 'distro.py', dest: '/opt/staging/gotty/', mode: '0400'}           # distro python module for login.py

- name: Create /etc/gotty/login.html from template
  # Replace the placeholder text in login.html.j2 with the FQDN.
  template:
    src: login.html.j2
    dest: /etc/gotty/login.html
    owner: root
    group: root
    mode: '0400'

- name: Open port 8080 in the firewall
  include_tasks: "{{ distro_abbreviation }}.yaml"

- name: Start and enable gotty service
# Start the gotty service and set it to start automatically on boot.
  systemd:
    name: gotty.service
    daemon-reload: yes
    state: started
    enabled: yes
