---
- name: Install knockd
# By naming the per-distro task files in a specific pattern, we don't need 
# conditional statements. See README.md for more info.
  include_tasks: "{{ item }}"
  with_first_found:
    - files: "{{ distro_abbreviation }}.yaml"
      skip: true

- name: Write knockd.conf file
# This file contains the definitions used to update the .LASTACTIVITY file
  template:
    src: knockd.conf.j2
    dest: /etc/knockd.conf
    owner: root
    group: root
    mode: '0644'

- name: Write knockd logrotate config
# knockd.log updates constantly so this config makes sure it gets rotated daily
# and doesn't grow too large.
  copy:
    src: knockd_logrotate
    dest: /etc/logrotate.d/knockd
    owner: root
    group: root
    mode: '0644'

- name: Start and enable knockd
  ignore_errors: yes
  systemd:
    name: knockd.service
    state: started
    enabled: yes
