---
- name: If testing, archive files before cleanup
# If we're running in test mode, we'll create a tar of all the files that
# will be deleted in the next task so we can reference them if we need to
# troubleshoot.
  community.general.archive:
    path:
      - /root/scvmmguestagent
      - /run/staging
      - /usr/local/sbin/sysprep
      - /opt/staging
      - /etc/staging
      - /root/.ansible
    dest: /tmp/staging.tgz
  when: test_mode | bool

- name: Cleanup
# Delete all the files that users shouldn't see and/or run.
  ignore_errors: yes
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /root/scvmmguestagent
    - /run/staging
    - /usr/local/sbin/sysprep
    - /opt/staging/initiator
    - /etc/staging/repo.yaml
