---
- name: Install bugfix/security updates
  ignore_errors: yes
  environment: 
    http_proxy: "{{ proxy_url }}"
    https_proxy: "{{ proxy_url }}"
    ACCEPT_EULA: 'Y' # Needed for non-interactive install of MS packages
  dnf:
    name: '*'
    security: yes
    bugfix: yes
    state: latest
