#!/usr/bin/env python3

if __name__ == '__main__':

    raspberry  = { 'r': 255, 'g':  74, 'b': 106 }  # Commvault raspberry
    amber      = { 'r': 255, 'g': 206, 'b': 108 }  # Commvault amber
    teal       = { 'r':   0, 'g': 178, 'b': 168 }  # Commvault teal
    periwinkle = { 'r':   0, 'g':  71, 'b': 187 }  # Commvault periwinkle
    indigo     = { 'r':  51, 'g':   5, 'b': 141 }  # Commvault indigo
    peacoat    = { 'r':  11, 'g':  45, 'b':  67 }  # Commvault peacoat

    hilight = raspberry

    def colorize(message, color=hilight):
        return (f"\033[38;2;{color['r']};{color['g']};{color['b']}m{message}\033[0m")

    print(f"""
    • {colorize('commvault start')}/{colorize('stop')}/{colorize('restart')} - Control Commvault services. 
    • {colorize('commvault list')} - Show running Commvault processes. 
    • {colorize('commvault status')} - Show Commvault instance info.

    • {colorize('systemctl start')}/{colorize('stop')}/{colorize('restart')}/{colorize('enable')}/{colorize('disable <service>')} - Control services.

    • {colorize('mssql-cli')} - Query the SQL database. Run {colorize('help')} within mssql-cli to see its commands.

    • {colorize('http')}/{colorize('https')} (HTTPie) - CLI HTTP client for REST API troubleshooting.
    • {colorize('jq')}/{colorize('jid')} - JSON filtering/querying utilities.

    • {colorize('setenforce 0')} - Put SELinux in permissive mode until reboot.

    • {colorize('firewall-cmd --list-ports')} - List open ports. 
    • {colorize('firewall-cmd --add-port <port>/<protocol> --permanent')} - Add an open port.
    • {colorize('firewall-cmd --reload')} - Reread configuration (activate newly added ports).

    • {colorize('tail')} - Tail log files in the terminal.
    • {colorize('multitail')} - Tail multiple logs in side-by-side panes.

    • {colorize('vi')}/{colorize('vim')} - The advanced text editor.
    • {colorize('nano')} - The basic text editor.
    • {colorize('less')} - Text viewer or "pager".

    • {colorize('tar')} - Create and unpack tar files, including those which are compressed (eg. tgz, txz, tbz2).
    • {colorize('7z')} (p7zip) - Unpack .zip, .7z, .rar, etc.

    • {colorize('dtach')} - Create and connect to persistent sessions that survive disconnects.

    For more detail, refer to {colorize('https://connect.commvault.com/docs/DOC-76482')}.
    """)
