---
- name: Install/Update python39 and pip
  ignore_errors: yes
  environment: 
    http_proxy: "{{ proxy_url }}"
    https_proxy: "{{ proxy_url }}"
  dnf:
    name: ["python39","python3-pip"]
    state: latest

- name: Update pip from pip3.6
  ignore_errors: yes
  environment: 
    http_proxy: "{{ proxy_url }}"
    https_proxy: "{{ proxy_url }}"
  pip:
    executable: pip3.6
    name: pip
    state: latest

- name: Update setuptools from pip3.6
  ignore_errors: yes
  environment:
    http_proxy: "{{ proxy_url }}"
    https_proxy: "{{ proxy_url }}"
  pip:
    executable: pip3.6
    name: setuptools
    state: latest

- name: Update pip from pip3.9
  ignore_errors: yes
  environment: 
    http_proxy: "{{ proxy_url }}"
    https_proxy: "{{ proxy_url }}"
  pip:
    executable: pip3.9
    name: pip
    state: latest

- name: Update setuptools from pip3.9
  ignore_errors: yes
  environment:
    http_proxy: "{{ proxy_url }}"
    https_proxy: "{{ proxy_url }}"
  pip:
    executable: pip3.9
    name: setuptools
    state: latest