---
- name: Schedule CarbonBlack Install
# Rather than holding up the staging process to do this now, we use atd to run
# it in the background 10 minutes from now.
  ignore_errors: yes
  at:
    command: "/usr/bin/wget -O - http://utcentos.commvault.com/CB-download-and-install-rhel.bash | bash > /var/log/staging/cb_install.log"
    count: 10
    units: minutes
    unique: yes
...