---
- name: Install httpie
  ignore_errors: yes
  environment: 
    # These environment variables allow internet access.
    http_proxy: "{{ proxy_url }}"
    https_proxy: "{{ proxy_url }}"
  community.general.pipx:
    executable: /usr/local/bin/pipx
    python: /usr/bin/python3.9
    name: httpie
    force: yes
...