---
- name: Install/Update p7zip
  ignore_errors: yes
  environment: 
    http_proxy: "{{ proxy_url }}"
    https_proxy: "{{ proxy_url }}"
  dnf:
    name: ["p7zip","p7zip-plugins"]
    state: latest
